# Configuración del servidor
spring.application.name=ProyectoFInal
server.port=8080
server.error.whitelabel.enabled=false



# Configuración de la base de datos H2
spring.datasource.url=jdbc:postgresql://zonaazul1.c3xgwl4lvs5y.us-east-1.rds.amazonaws.com:5432/zonaazul1
spring.datasource.username=zonaazul1
spring.datasource.password=zonaazul1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mvc.hiddenmethod.filter.enabled=true
spring.mvc.problemdetails.enabled=true


# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.client.registration.google.client-id=907151980785-ujbsomalmommltj3hpdld0r5oc9s3vvl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# URL de redirección después del login
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google


logging.level.org.springframework=DEBUG
logging.level.com.example.proyectofinal=DEBUG
logging.level.org.springframework.security=DEBUG














